// This file is automatically generated by qtc from "card.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line views/card.qtpl:1
package views

//line views/card.qtpl:3
import "github.com/jpincas/go-tea/examples/memorygame/types"

//line views/card.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/card.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/card.qtpl:5
func StreamRenderCard(qw422016 *qt422016.Writer, card types.Card) {
	//line views/card.qtpl:5
	qw422016.N().S(`

<div class="card 
        `)
	//line views/card.qtpl:8
	if card.Flipped {
		//line views/card.qtpl:8
		qw422016.N().S(` faceup `)
		//line views/card.qtpl:8
	} else {
		//line views/card.qtpl:8
		qw422016.N().S(` facedown `)
		//line views/card.qtpl:8
	}
	//line views/card.qtpl:8
	qw422016.N().S(`
        `)
	//line views/card.qtpl:9
	if card.Matched {
		//line views/card.qtpl:9
		qw422016.N().S(` matched `)
		//line views/card.qtpl:9
	} else {
		//line views/card.qtpl:9
		qw422016.N().S(` unmatched `)
		//line views/card.qtpl:9
	}
	//line views/card.qtpl:9
	qw422016.N().S(`">
    <span class="value">
        `)
	//line views/card.qtpl:11
	if card.Flipped {
		//line views/card.qtpl:11
		qw422016.N().S(` `)
		//line views/card.qtpl:11
		qw422016.N().D(card.Value)
		//line views/card.qtpl:11
		qw422016.N().S(` `)
		//line views/card.qtpl:11
	}
	//line views/card.qtpl:11
	qw422016.N().S(`
    </span>
</div>


`)
//line views/card.qtpl:16
}

//line views/card.qtpl:16
func WriteRenderCard(qq422016 qtio422016.Writer, card types.Card) {
	//line views/card.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/card.qtpl:16
	StreamRenderCard(qw422016, card)
	//line views/card.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line views/card.qtpl:16
}

//line views/card.qtpl:16
func RenderCard(card types.Card) string {
	//line views/card.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/card.qtpl:16
	WriteRenderCard(qb422016, card)
	//line views/card.qtpl:16
	qs422016 := string(qb422016.B)
	//line views/card.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/card.qtpl:16
	return qs422016
//line views/card.qtpl:16
}
