// This file is automatically generated by qtc from "deck.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line views/deck.qtpl:1
package views

//line views/deck.qtpl:3
import "github.com/jpincas/go-tea/examples/memorygame/types"

//line views/deck.qtpl:4
import "github.com/jpincas/go-tea"

//line views/deck.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/deck.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/deck.qtpl:6
func StreamRenderDeck(qw422016 *qt422016.Writer, deck types.Deck) {
	//line views/deck.qtpl:6
	qw422016.N().S(`

<div id="deck">
    `)
	//line views/deck.qtpl:9
	for index, thisCard := range deck {
		//line views/deck.qtpl:9
		qw422016.N().S(`
    <div class="card-container">

        `)
		//line views/deck.qtpl:12
		StreamRenderCard(qw422016, thisCard)
		//line views/deck.qtpl:12
		qw422016.N().S(` 
        
        `)
		//line views/deck.qtpl:14
		if !thisCard.Matched {
			//line views/deck.qtpl:14
			qw422016.N().S(`
        <button 
            class='flipcard gotea-click'
            data-msg='`)
			//line views/deck.qtpl:17
			qw422016.E().S(gotea.Msg(types.FlipCardMsg(index)))
			//line views/deck.qtpl:17
			qw422016.N().S(`'>
            Flip
        </button>
        `)
			//line views/deck.qtpl:20
		}
		//line views/deck.qtpl:20
		qw422016.N().S(`

    </div>
    `)
		//line views/deck.qtpl:23
	}
	//line views/deck.qtpl:23
	qw422016.N().S(`
</div>

`)
//line views/deck.qtpl:26
}

//line views/deck.qtpl:26
func WriteRenderDeck(qq422016 qtio422016.Writer, deck types.Deck) {
	//line views/deck.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/deck.qtpl:26
	StreamRenderDeck(qw422016, deck)
	//line views/deck.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line views/deck.qtpl:26
}

//line views/deck.qtpl:26
func RenderDeck(deck types.Deck) string {
	//line views/deck.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/deck.qtpl:26
	WriteRenderDeck(qb422016, deck)
	//line views/deck.qtpl:26
	qs422016 := string(qb422016.B)
	//line views/deck.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/deck.qtpl:26
	return qs422016
//line views/deck.qtpl:26
}
