// This file is automatically generated by qtc from "deck.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line views/deck.qtpl:1
package views

//line views/deck.qtpl:3
import "github.com/jpincas/go-tea/examples/memorygame/messages"

//line views/deck.qtpl:4
import "github.com/jpincas/go-tea/examples/memorygame/types"

//line views/deck.qtpl:5
import "github.com/jpincas/go-tea"

//line views/deck.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/deck.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/deck.qtpl:7
func StreamRenderDeck(qw422016 *qt422016.Writer, deck types.Deck) {
	//line views/deck.qtpl:7
	qw422016.N().S(`

<div id="deck">
    `)
	//line views/deck.qtpl:10
	for index, thisCard := range deck {
		//line views/deck.qtpl:10
		qw422016.N().S(`
    <div class="card-container">

        `)
		//line views/deck.qtpl:13
		StreamRenderCard(qw422016, thisCard)
		//line views/deck.qtpl:13
		qw422016.N().S(` 
        
        `)
		//line views/deck.qtpl:15
		if !thisCard.Matched {
			//line views/deck.qtpl:15
			qw422016.N().S(`
        <button 
            class='flipcard gotea-click'
            data-msg='`)
			//line views/deck.qtpl:18
			qw422016.E().S(gotea.Msg(messages.FlipCard(index)))
			//line views/deck.qtpl:18
			qw422016.N().S(`'>
            Flip
        </button>
        `)
			//line views/deck.qtpl:21
		}
		//line views/deck.qtpl:21
		qw422016.N().S(`

    </div>
    `)
		//line views/deck.qtpl:24
	}
	//line views/deck.qtpl:24
	qw422016.N().S(`
</div>

`)
//line views/deck.qtpl:27
}

//line views/deck.qtpl:27
func WriteRenderDeck(qq422016 qtio422016.Writer, deck types.Deck) {
	//line views/deck.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/deck.qtpl:27
	StreamRenderDeck(qw422016, deck)
	//line views/deck.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line views/deck.qtpl:27
}

//line views/deck.qtpl:27
func RenderDeck(deck types.Deck) string {
	//line views/deck.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/deck.qtpl:27
	WriteRenderDeck(qb422016, deck)
	//line views/deck.qtpl:27
	qs422016 := string(qb422016.B)
	//line views/deck.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/deck.qtpl:27
	return qs422016
//line views/deck.qtpl:27
}
