// This file is automatically generated by qtc from "main.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line main.qtpl:1
package main

//line main.qtpl:2
import "github.com/jpincas/go-tea"

//line main.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line main.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line main.qtpl:4
func StreamMain(qw422016 *qt422016.Writer, s gotea.Session) {
	//line main.qtpl:4
	qw422016.N().S(`

<h1>Global List with Broadcast Example</h1>

<button 
    class='gotea-click'
    data-msg='`)
	//line main.qtpl:10
	qw422016.E().S(gotea.Msg(AddCoordinate()))
	//line main.qtpl:10
	qw422016.N().S(`'>
        Add a Random Coordinate
</button>

<h2>Here's a list of coordinates:</h2>

<ul>
    `)
	//line main.qtpl:17
	for _, thisCoordinate := range *s.State.(Model).Coordinates {
		//line main.qtpl:17
		qw422016.N().S(`
        <li>X: `)
		//line main.qtpl:18
		qw422016.N().D(thisCoordinate.X)
		//line main.qtpl:18
		qw422016.N().S(`, Y: `)
		//line main.qtpl:18
		qw422016.N().D(thisCoordinate.Y)
		//line main.qtpl:18
		qw422016.N().S(`</li>
    `)
		//line main.qtpl:19
	}
	//line main.qtpl:19
	qw422016.N().S(`
</ul>

`)
//line main.qtpl:22
}

//line main.qtpl:22
func WriteMain(qq422016 qtio422016.Writer, s gotea.Session) {
	//line main.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line main.qtpl:22
	StreamMain(qw422016, s)
	//line main.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line main.qtpl:22
}

//line main.qtpl:22
func Main(s gotea.Session) string {
	//line main.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
	//line main.qtpl:22
	WriteMain(qb422016, s)
	//line main.qtpl:22
	qs422016 := string(qb422016.B)
	//line main.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
	//line main.qtpl:22
	return qs422016
//line main.qtpl:22
}
